Keep -iframework if present in parsed C/C++ flags
-iframework appears to implicitly add some header search paths to the
set specified using the -isystem, -I, and -isysroot flags. This means
that leaving out -iframework can result in invalid errors being
displayed.

For example, given a CMake project with this CMakeLists.txt:

    project(test)
    set(Qt5_DIR "/usr/local/opt/qt5/lib/cmake/Qt5")
    find_package(Qt5 5.9 REQUIRED COMPONENTS Widgets)
    add_executable(foo foo.cpp)
    target_link_libraries(foo PRIVATE Qt5::Widgets)

and foo.cpp:

    #include <QWidget>
    int main() {}

If g:ale_c_parse_compile_commands is set, then ALE executes something
along these lines:

    clang++ -S -x c++ -fsyntax-only -std=gnu++11 -isystem /usr/local/opt/qt5/lib/QtWidgets.framework/Headers - < foo.cpp

Resulting in this output:

    In file included from <stdin>:1:
    In file included from /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/QWidget:1:
    /usr/local/opt/qt5/lib/QtWidgets.framework/Headers/qwidget.h:43:10: fatal error: 'QtWidgets/qtwidgetsglobal.h' file not found
    #include <QtWidgets/qtwidgetsglobal.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Because the header is in a subdirectory of the path denoted by -isystem
(/usr/local/opt/qt5/lib/QtWidgets.framework/Headers/5.14.1/QtWidgets/qtwidgetsglobal.h),
clang fails to find it and exits.

If -iframework is included, ALE executes something along these lines:

    clang++ -S -x c++ -fsyntax-only -std=gnu++11 -iframework /usr/local/opt/qt5/lib -isystem /usr/local/opt/qt5/lib/QtWidgets.framework/Headers - < foo.cpp

And compilation completes successfully.